### ISSUE TITLE
How should we handle specs from multiple devices that overlap

### ISSUE THREAD

**Issue by elezar** [cncf-tags/container-device-interface#41]
Consider the following spec example:

```yaml
---
cdiVersion: 0.2.0
kind: nvidia.com/gpu
devices:
- name: gpu0
  containerEdits:
    env:
    - NVIDIA_VISIBLE_DEVICES=0
- name: gpu1
  containerEdits:
    env:
    - NVIDIA_VISIBLE_DEVICES=1
containerEdits:
  hooks:
  - hookName: prestart
    path: "/usr/bin/nvidia-container-toolkit"
    args:
    - nvidia-container-toolkit
    - prestart
```
This has two devices: `nvidia.com/gpu=gpu0` and `nvidia.com/gpu=gpu1` that can be selected. With the current implementation these devices can be used independently, but since they both inject the same environment variable into the container being created, they cannot be used together.

How do we handle merging of specs from multiple devices where these overlap? In this case adding a device:
```yaml
- name: gpu0and1
  containerEdits:
    env:
    - NVIDIA_VISIBLE_DEVICES=0,1
```
would allow both to be available in the container, but doing this for all combinations of devices with a high number of devices is not feasible.

**Comment by klueska** [comment]
One way would be to leverage "accept-nvidia-visible-devices-as-volume-mounts" instead of as an ENVVAR:
https://docs.google.com/document/d/1zy0key-EL6JH50MZgwg96RPYxxXXnVUdxLZwGiyqLd8/edit

**Comment by klihub** [comment]
If a CDI Spec has conflicting environment variables for multiple devices, then this is going to be a problem. IIUC your example what you try to do here with the env. vars is pointing out injected or to be injected devices, either for the container of for some vendor-specific component/middle-ware. I think you could avoid this clash problem altogether by using multiple environment variables with a common well-known prefix and collect (multiple) values by evaluating those, instead of trying to dig out multiple values from evaluating a single environment variable.

**Comment by klihub** [comment]
> The goal of what Evan is trying to do here is to use CDI to trigger the existing NVIDIA container stack to do device injection rather than encoding all of the device mounts, lib mounts, etc. directly in the CDI file. the NVIDIA container stack knows which GPUs to inject by looking at the _single_ environment variable `NVIDIA_VISIBLE_DEVICES`, which lists the GPUs you want injected into the container.

Ok, thanks for the context. So the single environment variable is an invariant limitation imposed on us by an existing software stack, which we try to bend to our will using CDI (container edits).

> 
> It sounds like CDI doesn't support this at the moment, but I don't see any reason it couldn't.
> 
> Environment variables in the OCI runtime spec are [stored as a list](https://github.com/opencontainers/runtime-spec/blob/main/specs-go/config.go#L47), not a map, so it would be perfectly reasonable to insert both envvars from both devices without conflict, i.e.:
> 
> ```
> Spec.Process.Env = []string{
>     "NVIDIA_VISIBLE_DEVICES=0",
>     "NVIDIA_VISIBLE_DEVICES=1",
> }
> ```

The problem with that idea is that even if we alter the OCI Spec in CDI like that, it might not survive being processed in the runtime by the [OCI Spec generator](https://github.com/opencontainers/runtime-tools/blob/master/generate/generate.go) which is pretty insistent on filtering out duplicate keys from the environment. At least one of the prominent runtimes does use the Spec generator.

So instead, my suggestion would be to update/extend the CDI Spec to allow exactly what we need here: appending to the value of an existing environment variable instead of blindly overwriting it. It probably requires some head-scratching (to come up with a proper notation that allows things like specifying a separator but is not butt-ugly to use), but I think this would be a safer/saner way forward than misusing some unintentional/undefined feature of the current OCI Spec version. 

Since the environment edits in CDI are simply a `Env []string`, maybe we could simply use a `+=` notation instead of a `=` to indicate appending, where the first character is the separator which is omitted if the environment variable does not exist or is empty. So in your case, the CDI Spec could contain something like this

```
...
  devices:
  - name: gpu0
    containerEdits:
      env:
      - "NVIDIA_VISIBLE_DEVICES+=,0"
...     
  - name: gpu1
    containerEdits:
      env:
      - "NVIDIA_VISIBLE_DEVICES+=,1"
...
```

> 
> Then it would be up to whoever consumes the spec to merge these / do what it sees fit with them. In our case, we could update the code [here](https://github.com/NVIDIA/nvidia-container-toolkit/blob/b23e3ea13a22f6f22012230e76b5210e1afefec2/internal/config/image/cuda_image.go#L53) to merge them as necessary.

I thought modifying existing code was out of the question. If there is a piece of code that could be modified to merge multiple environment variables with identical keys/names in the OCI Spec, then I don't understand why that same piece of code couldn't be modified to go through the environment and replace any set of NVIDIA_VISIBLE_DEVICES_{0,...,N} found, with a single NVIDIA_VISIBLE_DEVICES variable that has as its value the comma-separated values of all those replaced variables.
